Add `httpsoft` tests
php-http/psr7-integration-tests pull request #73
Opened 2023-05-23 14:35 UTC by vjik

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| Documentation   | -
| License         | MIT

2023-05-24 05:39 UTC, dbu commented on phpunit.xml.dist
> +        <directory>./tests/HttpSoft/</directory>
as you implement the test integration in your repository, i think we can do the same as with nyholm:
```suggestion
        <directory>./vendor/httpsoft/http-message/tests/Integration/</directory>
```

2023-05-24 05:40 UTC, dbu commented on phpunit.xml.dist
> +        <directory>./tests/HttpSoft/</directory>
if that is indeed possible, you can remove the test integrations in tests/HttpSoft from this PR

2023-05-24 05:41 UTC, dbu commented
thanks, cool! looking at the test output, there seems to be one issue with stream setup, otherwise httpsoft passes all tests :+1:

2023-05-24 18:32 UTC, vjik commented on phpunit.xml.dist
> +        <directory>./tests/HttpSoft/</directory>
Is it right? 
 
 `php-http/psr7-integration-tests` should test implementations with latest version of tests, but tests from tested package may be non-actual.

2023-05-24 18:45 UTC, dbu commented on phpunit.xml.dist
> +        <directory>./tests/HttpSoft/</directory>
the classes from the httpsoft package only set up the tests defined in this repository. i think as long as we don't mess up BC we should be fine (and if we mess that up, it would be even more a problem if we only adjust the integration here but not in the httpsoft package)

it was "good enough" for the nyholm package, imho we can do the same with httpsoft.

2023-05-24 19:33 UTC, vjik commented on phpunit.xml.dist
> +        <directory>./tests/HttpSoft/</directory>
Done

2023-05-25 12:07 UTC, dbu requested changes
thanks. i think you need to add a case for the httpsoft stream factory in src/BaseTest, like you did for UriFactory. then the remaining failures should be fixed.

2023-05-25 14:13 UTC, vjik commented
> thanks. i think you need to add a case for the httpsoft stream factory in src/BaseTest, like you did for UriFactory. then the remaining failures should be fixed.

Done.

2023-05-25 14:22 UTC, dbu approved these changes
cheers!

2023-05-25 14:22 UTC, merged